// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BagCommon.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rpg.Proto.Bag {

  /// <summary>Holder for reflection information generated from BagCommon.proto</summary>
  public static partial class BagCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for BagCommon.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BagCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9CYWdDb21tb24ucHJvdG8SB3JwZy5iYWcqVAoJQmFnTXNnU3ViEhsKF0JB",
            "R19NU0dfU1VCX1VOU1BFQ0lGSUVEEAASFAoQQzJTX0JBR19JTkZPX1JFURAB",
            "EhQKEFMyQ19CQUdfSU5GT19SU1AQAkIQqgINUnBnLlByb3RvLkJhZ2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Rpg.Proto.Bag.BagMsgSub), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum BagMsgSub {
    [pbr::OriginalName("BAG_MSG_SUB_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// 0x01 C→S 请求背包
    /// </summary>
    [pbr::OriginalName("C2S_BAG_INFO_REQ")] C2SBagInfoReq = 1,
    /// <summary>
    /// 0x02 S→C 背包同步
    /// </summary>
    [pbr::OriginalName("S2C_BAG_INFO_RSP")] S2CBagInfoRsp = 2,
  }

  #endregion

}

#endregion Designer generated code
