// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ChatCommon.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rpg.Proto.Chat {

  /// <summary>Holder for reflection information generated from ChatCommon.proto</summary>
  public static partial class ChatCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for ChatCommon.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChatCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBDaGF0Q29tbW9uLnByb3RvEghycGcuY2hhdCp+CgpDaGF0TXNnU3ViEhwK",
            "GENIQVRfTVNHX1NVQl9VTlNQRUNJRklFRBAAEhAKDEMyU19DSEFUX1JFURAB",
            "EhMKD1MyQ19DSEFUX05PVElGWRACEhMKD0MyU19XSElTUEVSX1JFURADEhYK",
            "ElMyQ19XSElTUEVSX05PVElGWRAEKmsKC0NoYXRDaGFubmVsEhYKEkNIQVRf",
            "Q0hBTk5FTF9XT1JMRBAAEhUKEUNIQVRfQ0hBTk5FTF9aT05FEAESFQoRQ0hB",
            "VF9DSEFOTkVMX1RFQU0QAhIWChJDSEFUX0NIQU5ORUxfR1VJTEQQA0IRqgIO",
            "UnBnLlByb3RvLkNoYXRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Rpg.Proto.Chat.ChatMsgSub), typeof(global::Rpg.Proto.Chat.ChatChannel), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ChatMsgSub {
    [pbr::OriginalName("CHAT_MSG_SUB_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// 0x01 C→S 频道聊天；SceneServer
    /// </summary>
    [pbr::OriginalName("C2S_CHAT_REQ")] C2SChatReq = 1,
    /// <summary>
    /// 0x02 S→C 聊天广播；SceneServer
    /// </summary>
    [pbr::OriginalName("S2C_CHAT_NOTIFY")] S2CChatNotify = 2,
    /// <summary>
    /// 0x03 未实现
    /// </summary>
    [pbr::OriginalName("C2S_WHISPER_REQ")] C2SWhisperReq = 3,
    /// <summary>
    /// 0x04 未实现
    /// </summary>
    [pbr::OriginalName("S2C_WHISPER_NOTIFY")] S2CWhisperNotify = 4,
  }

  public enum ChatChannel {
    [pbr::OriginalName("CHAT_CHANNEL_WORLD")] World = 0,
    [pbr::OriginalName("CHAT_CHANNEL_ZONE")] Zone = 1,
    [pbr::OriginalName("CHAT_CHANNEL_TEAM")] Team = 2,
    [pbr::OriginalName("CHAT_CHANNEL_GUILD")] Guild = 3,
  }

  #endregion

}

#endregion Designer generated code
