// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NpcCommon.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rpg.Proto.Npc {

  /// <summary>Holder for reflection information generated from NpcCommon.proto</summary>
  public static partial class NpcCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for NpcCommon.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NpcCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9OcGNDb21tb24ucHJvdG8SB3JwZy5ucGMqVAoJTnBjTXNnU3ViEhsKF05Q",
            "Q19NU0dfU1VCX1VOU1BFQ0lGSUVEEAASFAoQQzJTX05QQ19UQUxLX1JFURAB",
            "EhQKEFMyQ19OUENfVEFMS19SU1AQAkIQqgINUnBnLlByb3RvLk5wY2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Rpg.Proto.Npc.NpcMsgSub), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum NpcMsgSub {
    [pbr::OriginalName("NPC_MSG_SUB_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// 0x01 C→S NPC 对话；SceneServer→Lua
    /// </summary>
    [pbr::OriginalName("C2S_NPC_TALK_REQ")] C2SNpcTalkReq = 1,
    /// <summary>
    /// 0x02 S→C 对话响应；SceneServer
    /// </summary>
    [pbr::OriginalName("S2C_NPC_TALK_RSP")] S2CNpcTalkRsp = 2,
  }

  #endregion

}

#endregion Designer generated code
