// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: QuestCommon.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rpg.Proto.Quest {

  /// <summary>Holder for reflection information generated from QuestCommon.proto</summary>
  public static partial class QuestCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for QuestCommon.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QuestCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFRdWVzdENvbW1vbi5wcm90bxIJcnBnLnF1ZXN0KmwKC1F1ZXN0TXNnU3Vi",
            "Eh0KGVFVRVNUX01TR19TVUJfVU5TUEVDSUZJRUQQABIUChBDMlNfUVVFU1Rf",
            "QUNDRVBUEAESFAoQQzJTX1FVRVNUX1NVQk1JVBACEhIKDlMyQ19RVUVTVF9J",
            "TkZPEANCEqoCD1JwZy5Qcm90by5RdWVzdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Rpg.Proto.Quest.QuestMsgSub), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum QuestMsgSub {
    [pbr::OriginalName("QUEST_MSG_SUB_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// 0x01 C→S 接取任务
    /// </summary>
    [pbr::OriginalName("C2S_QUEST_ACCEPT")] C2SQuestAccept = 1,
    /// <summary>
    /// 0x02 C→S 提交任务
    /// </summary>
    [pbr::OriginalName("C2S_QUEST_SUBMIT")] C2SQuestSubmit = 2,
    /// <summary>
    /// 0x03 S→C 任务列表同步
    /// </summary>
    [pbr::OriginalName("S2C_QUEST_INFO")] S2CQuestInfo = 3,
  }

  #endregion

}

#endregion Designer generated code
