// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SystemCommon.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rpg.Proto.System {

  /// <summary>Holder for reflection information generated from SystemCommon.proto</summary>
  public static partial class SystemCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for SystemCommon.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SystemCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJTeXN0ZW1Db21tb24ucHJvdG8SCnJwZy5zeXN0ZW0qgQEKDFN5c3RlbU1z",
            "Z1N1YhIeChpTWVNURU1fTVNHX1NVQl9VTlNQRUNJRklFRBAAEhEKDUMyU19I",
            "RUFSVEJFQVQQARIRCg1TMkNfSEVBUlRCRUFUEAISDAoIUzJDX0tJQ0sQAxIO",
            "CgpTMkNfTk9USUNFEAQSDQoJUzJDX0VSUk9SEAUq1gEKE0dhdGV3YXlWYWxp",
            "ZGF0ZUNvZGUSFwoTR0FURVdBWV9WQUxJREFURV9PSxAAEiAKHEdBVEVXQVlf",
            "VkFMSURBVEVfVU5LTk9XTl9NU0cQARIfChtHQVRFV0FZX1ZBTElEQVRFX0JB",
            "RF9MRU5HVEgQAhIeChpHQVRFV0FZX1ZBTElEQVRFX0JBRF9TVEFURRADEiAK",
            "HEdBVEVXQVlfVkFMSURBVEVfQkFEX1BBWUxPQUQQBBIhCh1HQVRFV0FZX1ZB",
            "TElEQVRFX1JBVEVfTElNSVRFRBAFQhOqAhBScGcuUHJvdG8uU3lzdGVtYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Rpg.Proto.System.SystemMsgSub), typeof(global::Rpg.Proto.System.GatewayValidateCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum SystemMsgSub {
    [pbr::OriginalName("SYSTEM_MSG_SUB_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// 0x01 C→S 心跳
    /// </summary>
    [pbr::OriginalName("C2S_HEARTBEAT")] C2SHeartbeat = 1,
    /// <summary>
    /// 0x02 S→C 心跳响应
    /// </summary>
    [pbr::OriginalName("S2C_HEARTBEAT")] S2CHeartbeat = 2,
    /// <summary>
    /// 0x03 S→C 踢线
    /// </summary>
    [pbr::OriginalName("S2C_KICK")] S2CKick = 3,
    /// <summary>
    /// 0x04 S→C 系统公告
    /// </summary>
    [pbr::OriginalName("S2C_NOTICE")] S2CNotice = 4,
    /// <summary>
    /// 0x05 S→C 网关校验错误
    /// </summary>
    [pbr::OriginalName("S2C_ERROR")] S2CError = 5,
  }

  public enum GatewayValidateCode {
    [pbr::OriginalName("GATEWAY_VALIDATE_OK")] GatewayValidateOk = 0,
    [pbr::OriginalName("GATEWAY_VALIDATE_UNKNOWN_MSG")] GatewayValidateUnknownMsg = 1,
    [pbr::OriginalName("GATEWAY_VALIDATE_BAD_LENGTH")] GatewayValidateBadLength = 2,
    [pbr::OriginalName("GATEWAY_VALIDATE_BAD_STATE")] GatewayValidateBadState = 3,
    [pbr::OriginalName("GATEWAY_VALIDATE_BAD_PAYLOAD")] GatewayValidateBadPayload = 4,
    [pbr::OriginalName("GATEWAY_VALIDATE_RATE_LIMITED")] GatewayValidateRateLimited = 5,
  }

  #endregion

}

#endregion Designer generated code
