// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ZoneCommon.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rpg.Proto.Zone {

  /// <summary>Holder for reflection information generated from ZoneCommon.proto</summary>
  public static partial class ZoneCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for ZoneCommon.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ZoneCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBab25lQ29tbW9uLnByb3RvEghycGcuem9uZSpYCgpab25lTXNnU3ViEhwK",
            "GFpPTkVfTVNHX1NVQl9VTlNQRUNJRklFRBAAEhUKEUMyU19aT05FX0xJU1Rf",
            "UkVREAsSFQoRUzJDX1pPTkVfTElTVF9SU1AQDCpoCg1ab25lTG9hZExldmVs",
            "EhQKEFpPTkVfTE9BRF9TTU9PVEgQABISCg5aT05FX0xPQURfQlVTWRABEhIK",
            "DlpPTkVfTE9BRF9GVUxMEAISGQoVWk9ORV9MT0FEX01BSU5URU5BTkNFEANC",
            "EaoCDlJwZy5Qcm90by5ab25lYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Rpg.Proto.Zone.ZoneMsgSub), typeof(global::Rpg.Proto.Zone.ZoneLoadLevel), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ZoneMsgSub {
    [pbr::OriginalName("ZONE_MSG_SUB_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// 0x0B C→S 区列表；LoginServer
    /// </summary>
    [pbr::OriginalName("C2S_ZONE_LIST_REQ")] C2SZoneListReq = 11,
    /// <summary>
    /// 0x0C S→C 区列表；LoginServer
    /// </summary>
    [pbr::OriginalName("S2C_ZONE_LIST_RSP")] S2CZoneListRsp = 12,
  }

  public enum ZoneLoadLevel {
    [pbr::OriginalName("ZONE_LOAD_SMOOTH")] ZoneLoadSmooth = 0,
    [pbr::OriginalName("ZONE_LOAD_BUSY")] ZoneLoadBusy = 1,
    [pbr::OriginalName("ZONE_LOAD_FULL")] ZoneLoadFull = 2,
    [pbr::OriginalName("ZONE_LOAD_MAINTENANCE")] ZoneLoadMaintenance = 3,
  }

  #endregion

}

#endregion Designer generated code
