// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LoginCommon.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rpg.Proto.Login {

  /// <summary>Holder for reflection information generated from LoginCommon.proto</summary>
  public static partial class LoginCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for LoginCommon.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LoginCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFMb2dpbkNvbW1vbi5wcm90bxIJcnBnLmxvZ2luKsgCCgtMb2dpbk1zZ1N1",
            "YhIdChlMT0dJTl9NU0dfU1VCX1VOU1BFQ0lGSUVEEAASEQoNQzJTX0xPR0lO",
            "X1JFURABEhEKDVMyQ19MT0dJTl9SU1AQAhIUChBDMlNfUkVHSVNURVJfUkVR",
            "EAMSFAoQUzJDX1JFR0lTVEVSX1JTUBAEEhcKE0MyU19TRUxFQ1RfVVNFUl9S",
            "RVEQBRIRCg1TMkNfVVNFUl9MSVNUEAYSFwoTQzJTX0NSRUFURV9VU0VSX1JF",
            "URAHEhcKE1MyQ19DUkVBVEVfVVNFUl9SU1AQCBISCg5TMkNfRU5URVJfR0FN",
            "RRAJEhQKEFMyQ19HQVRFV0FZX0lORk8QChIYChRDMlNfR0FURVdBWV9BVVRI",
            "X1JFURANEhIKDkMyU19MT0dPVVRfUkVREA4SEgoOUzJDX0xPR09VVF9SU1AQ",
            "DypXCgxMb2dvdXRBY3Rpb24SHQoZTE9HT1VUX0FDVElPTl9VTlNQRUNJRklF",
            "RBAAEhYKElJFVFVSTl9DSEFSX1NFTEVDVBABEhAKDFJFVFVSTl9MT0dJThAC",
            "KlkKD0xvZ2luUmVzdWx0Q29kZRITCg9MT0dJTl9SRVNVTFRfT0sQABIZChVM",
            "T0dJTl9CQURfQ1JFREVOVElBTFMQARIWChJMT0dJTl9TRVJWRVJfRVJST1IQ",
            "AipdChJSZWdpc3RlclJlc3VsdENvZGUSDwoLUkVHSVNURVJfT0sQABIbChdS",
            "RUdJU1RFUl9BQ0NPVU5UX0VYSVNUUxABEhkKFVJFR0lTVEVSX1NFUlZFUl9F",
            "UlJPUhACKnwKGUNyZWF0ZUNoYXJhY3RlclJlc3VsdENvZGUSFwoTQ1JFQVRF",
            "X0NIQVJBQ1RFUl9PSxAAEiMKH0NSRUFURV9DSEFSQUNURVJfRFVQTElDQVRF",
            "X05BTUUQARIhCh1DUkVBVEVfQ0hBUkFDVEVSX1NFUlZFUl9FUlJPUhACKkkK",
            "FUdhdGV3YXlJbmZvUmVzdWx0Q29kZRITCg9HQVRFV0FZX0lORk9fT0sQABIb",
            "ChdHQVRFV0FZX0lORk9fTk9fR0FURVdBWRABKkIKElVzZXJMaXN0UmVzdWx0",
            "Q29kZRIQCgxVU0VSX0xJU1RfT0sQABIaChZVU0VSX0xJU1RfU0VSVkVSX0VS",
            "Uk9SEAEqNAoQTG9nb3V0UmVzdWx0Q29kZRINCglMT0dPVVRfT0sQABIRCg1M",
            "T0dPVVRfRkFJTEVEEAFCEqoCD1JwZy5Qcm90by5Mb2dpbmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Rpg.Proto.Login.LoginMsgSub), typeof(global::Rpg.Proto.Login.LogoutAction), typeof(global::Rpg.Proto.Login.LoginResultCode), typeof(global::Rpg.Proto.Login.RegisterResultCode), typeof(global::Rpg.Proto.Login.CreateCharacterResultCode), typeof(global::Rpg.Proto.Login.GatewayInfoResultCode), typeof(global::Rpg.Proto.Login.UserListResultCode), typeof(global::Rpg.Proto.Login.LogoutResultCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 登录域子编号（module=LOGIN/0x00）
  /// </summary>
  public enum LoginMsgSub {
    [pbr::OriginalName("LOGIN_MSG_SUB_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// 0x01 C→S 账号登录；LoginServer
    /// </summary>
    [pbr::OriginalName("C2S_LOGIN_REQ")] C2SLoginReq = 1,
    /// <summary>
    /// 0x02 S→C 登录结果；LoginServer
    /// </summary>
    [pbr::OriginalName("S2C_LOGIN_RSP")] S2CLoginRsp = 2,
    /// <summary>
    /// 0x03 C→S 注册；LoginServer
    /// </summary>
    [pbr::OriginalName("C2S_REGISTER_REQ")] C2SRegisterReq = 3,
    /// <summary>
    /// 0x04 S→C 注册结果；LoginServer
    /// </summary>
    [pbr::OriginalName("S2C_REGISTER_RSP")] S2CRegisterRsp = 4,
    /// <summary>
    /// 0x05 C→S 选角进世界；Gateway→Super
    /// </summary>
    [pbr::OriginalName("C2S_SELECT_USER_REQ")] C2SSelectUserReq = 5,
    /// <summary>
    /// 0x06 S→C 角色列表；Gateway
    /// </summary>
    [pbr::OriginalName("S2C_USER_LIST")] S2CUserList = 6,
    /// <summary>
    /// 0x07 C→S 创角；Gateway→Record
    /// </summary>
    [pbr::OriginalName("C2S_CREATE_USER_REQ")] C2SCreateUserReq = 7,
    /// <summary>
    /// 0x08 S→C 创角结果；Gateway
    /// </summary>
    [pbr::OriginalName("S2C_CREATE_USER_RSP")] S2CCreateUserRsp = 8,
    /// <summary>
    /// 0x09 S→C 进世界；Gateway
    /// </summary>
    [pbr::OriginalName("S2C_ENTER_GAME")] S2CEnterGame = 9,
    /// <summary>
    /// 0x0A S→C 网关地址；LoginServer
    /// </summary>
    [pbr::OriginalName("S2C_GATEWAY_INFO")] S2CGatewayInfo = 10,
    /// <summary>
    /// 0x0D C→S Gateway 票据鉴权；Gateway
    /// </summary>
    [pbr::OriginalName("C2S_GATEWAY_AUTH_REQ")] C2SGatewayAuthReq = 13,
    /// <summary>
    /// 0x0E C→S 离世界；Gateway
    /// </summary>
    [pbr::OriginalName("C2S_LOGOUT_REQ")] C2SLogoutReq = 14,
    /// <summary>
    /// 0x0F S→C 离世界响应；Gateway
    /// </summary>
    [pbr::OriginalName("S2C_LOGOUT_RSP")] S2CLogoutRsp = 15,
  }

  public enum LogoutAction {
    [pbr::OriginalName("LOGOUT_ACTION_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// 回选角，保持 Gateway 账号会话
    /// </summary>
    [pbr::OriginalName("RETURN_CHAR_SELECT")] ReturnCharSelect = 1,
    /// <summary>
    /// 回登录 UI，随后断 Gateway
    /// </summary>
    [pbr::OriginalName("RETURN_LOGIN")] ReturnLogin = 2,
  }

  public enum LoginResultCode {
    [pbr::OriginalName("LOGIN_RESULT_OK")] LoginResultOk = 0,
    [pbr::OriginalName("LOGIN_BAD_CREDENTIALS")] LoginBadCredentials = 1,
    /// <summary>
    /// legacy wire -1 映射为此值或直接用 int32 code
    /// </summary>
    [pbr::OriginalName("LOGIN_SERVER_ERROR")] LoginServerError = 2,
  }

  public enum RegisterResultCode {
    [pbr::OriginalName("REGISTER_OK")] RegisterOk = 0,
    [pbr::OriginalName("REGISTER_ACCOUNT_EXISTS")] RegisterAccountExists = 1,
    [pbr::OriginalName("REGISTER_SERVER_ERROR")] RegisterServerError = 2,
  }

  public enum CreateCharacterResultCode {
    [pbr::OriginalName("CREATE_CHARACTER_OK")] CreateCharacterOk = 0,
    [pbr::OriginalName("CREATE_CHARACTER_DUPLICATE_NAME")] CreateCharacterDuplicateName = 1,
    [pbr::OriginalName("CREATE_CHARACTER_SERVER_ERROR")] CreateCharacterServerError = 2,
  }

  public enum GatewayInfoResultCode {
    [pbr::OriginalName("GATEWAY_INFO_OK")] GatewayInfoOk = 0,
    [pbr::OriginalName("GATEWAY_INFO_NO_GATEWAY")] GatewayInfoNoGateway = 1,
  }

  public enum UserListResultCode {
    [pbr::OriginalName("USER_LIST_OK")] UserListOk = 0,
    [pbr::OriginalName("USER_LIST_SERVER_ERROR")] UserListServerError = 1,
  }

  public enum LogoutResultCode {
    [pbr::OriginalName("LOGOUT_OK")] LogoutOk = 0,
    [pbr::OriginalName("LOGOUT_FAILED")] LogoutFailed = 1,
  }

  #endregion

}

#endregion Designer generated code
