// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MapDataCommon.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rpg.Proto.MapData {

  /// <summary>Holder for reflection information generated from MapDataCommon.proto</summary>
  public static partial class MapDataCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for MapDataCommon.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MapDataCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNNYXBEYXRhQ29tbW9uLnByb3RvEgtycGcubWFwZGF0YSqGAQoNTWFwRGF0",
            "YU1zZ1N1YhIgChxNQVBfREFUQV9NU0dfU1VCX1VOU1BFQ0lGSUVEEAASEAoM",
            "QzJTX01PVkVfUkVREAESEwoPUzJDX01PVkVfTk9USUZZEAISFAoQUzJDX1NQ",
            "QVdOX0VOVElUWRAFEhYKElMyQ19ERVNQQVdOX0VOVElUWRAGKkwKCE1vdmVU",
            "eXBlEhkKFU1PVkVfVFlQRV9VTlNQRUNJRklFRBAAEhIKDk1PVkVfVFlQRV9X",
            "QUxLEAESEQoNTU9WRV9UWVBFX1JVThACKpoBCgpFbnRpdHlUeXBlEhsKF0VO",
            "VElUWV9UWVBFX1VOU1BFQ0lGSUVEEAASFgoSRU5USVRZX1RZUEVfUExBWUVS",
            "EAESEwoPRU5USVRZX1RZUEVfTlBDEAISFwoTRU5USVRZX1RZUEVfTU9OU1RF",
            "UhADEhMKD0VOVElUWV9UWVBFX1BFVBAEEhQKEEVOVElUWV9UWVBFX0lURU0Q",
            "BUIUqgIRUnBnLlByb3RvLk1hcERhdGFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Rpg.Proto.MapData.MapDataMsgSub), typeof(global::Rpg.Proto.MapData.MoveType), typeof(global::Rpg.Proto.MapData.EntityType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 场景域子编号（module=SCENE/0x01）
  /// </summary>
  public enum MapDataMsgSub {
    [pbr::OriginalName("MAP_DATA_MSG_SUB_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// 0x01 C→S 移动请求；Gateway→SceneServer
    /// </summary>
    [pbr::OriginalName("C2S_MOVE_REQ")] C2SMoveReq = 1,
    /// <summary>
    /// 0x02 S→C 移动广播；Scene→Gateway→客户端
    /// </summary>
    [pbr::OriginalName("S2C_MOVE_NOTIFY")] S2CMoveNotify = 2,
    /// <summary>
    /// 0x05 S→C 实体进视野；Scene→Gateway
    /// </summary>
    [pbr::OriginalName("S2C_SPAWN_ENTITY")] S2CSpawnEntity = 5,
    /// <summary>
    /// 0x06 S→C 实体出视野；Scene→Gateway
    /// </summary>
    [pbr::OriginalName("S2C_DESPAWN_ENTITY")] S2CDespawnEntity = 6,
  }

  /// <summary>
  /// 移动类型（C2SMoveReq.move_type）
  /// </summary>
  public enum MoveType {
    [pbr::OriginalName("MOVE_TYPE_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// 走；步长见 map.meta.json maxStepWalk
    /// </summary>
    [pbr::OriginalName("MOVE_TYPE_WALK")] Walk = 1,
    /// <summary>
    /// 跑；步长见 maxStepRun
    /// </summary>
    [pbr::OriginalName("MOVE_TYPE_RUN")] Run = 2,
  }

  /// <summary>
  /// 实体类型（S2CSpawnEntity.entity_type）
  /// </summary>
  public enum EntityType {
    [pbr::OriginalName("ENTITY_TYPE_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// 玩家
    /// </summary>
    [pbr::OriginalName("ENTITY_TYPE_PLAYER")] Player = 1,
    /// <summary>
    /// NPC
    /// </summary>
    [pbr::OriginalName("ENTITY_TYPE_NPC")] Npc = 2,
    /// <summary>
    /// 怪物
    /// </summary>
    [pbr::OriginalName("ENTITY_TYPE_MONSTER")] Monster = 3,
    /// <summary>
    /// 宠物
    /// </summary>
    [pbr::OriginalName("ENTITY_TYPE_PET")] Pet = 4,
    /// <summary>
    /// 地面物品
    /// </summary>
    [pbr::OriginalName("ENTITY_TYPE_ITEM")] Item = 5,
  }

  #endregion

}

#endregion Designer generated code
