// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WireCommon.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rpg.Proto.Client {

  /// <summary>Holder for reflection information generated from WireCommon.proto</summary>
  public static partial class WireCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for WireCommon.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WireCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBXaXJlQ29tbW9uLnByb3RvEgpycGcuY2xpZW50Ij4KDVdpcmVNc2dIZWFk",
            "ZXISEAoIYm9keV9sZW4YASABKA0SDgoGbW9kdWxlGAIgASgNEgsKA3N1YhgD",
            "IAEoDSrAAQoPV2lyZUJ1ZmZlckxpbWl0EiEKHVdJUkVfQlVGRkVSX0xJTUlU",
            "X1VOU1BFQ0lGSUVEEAASFQoPTUFYX1BBQ0tFVF9TSVpFEP//AxIWChBSRUNW",
            "X0JVRkZFUl9TSVpFEICACBIWChBTRU5EX0JVRkZFUl9TSVpFEICACBIVChBN",
            "QVhfRVBPTExfRVZFTlRTEIAIEhMKDkxJU1RFTl9CQUNLTE9HEIAEEhMKD01T",
            "R19IRUFERVJfU0laRRAEGgIQASopChJXaXJlQ29ubklkQ29uc3RhbnQSEwoP",
            "SU5WQUxJRF9DT05OX0lEEABCE6oCEFJwZy5Qcm90by5DbGllbnRiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Rpg.Proto.Client.WireBufferLimit), typeof(global::Rpg.Proto.Client.WireConnIdConstant), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Rpg.Proto.Client.WireMsgHeader), global::Rpg.Proto.Client.WireMsgHeader.Parser, new[]{ "BodyLen", "Module", "Sub" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 缓冲区与帧上限（与 sdk/net/NetDefine.h 数值一致）
  /// </summary>
  public enum WireBufferLimit {
    [pbr::OriginalName("WIRE_BUFFER_LIMIT_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("MAX_PACKET_SIZE")] MaxPacketSize = 65535,
    [pbr::OriginalName("RECV_BUFFER_SIZE")] RecvBufferSize = 131072,
    [pbr::OriginalName("SEND_BUFFER_SIZE", PreferredAlias = false)] SendBufferSize = 131072,
    [pbr::OriginalName("MAX_EPOLL_EVENTS")] MaxEpollEvents = 1024,
    [pbr::OriginalName("LISTEN_BACKLOG")] ListenBacklog = 512,
    [pbr::OriginalName("MSG_HEADER_SIZE")] MsgHeaderSize = 4,
  }

  /// <summary>
  /// 连接 ID 约定（ConnID = uint32；0 表示无效）
  /// </summary>
  public enum WireConnIdConstant {
    [pbr::OriginalName("INVALID_CONN_ID")] InvalidConnId = 0,
  }

  #endregion

  #region Messages
  /// <summary>
  /// TCP 帧头逻辑视图（线上为 4 字节 packed：uint16 body_len LE + uint8 module + uint8 sub）
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WireMsgHeader : pb::IMessage<WireMsgHeader>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WireMsgHeader> _parser = new pb::MessageParser<WireMsgHeader>(() => new WireMsgHeader());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WireMsgHeader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rpg.Proto.Client.WireCommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WireMsgHeader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WireMsgHeader(WireMsgHeader other) : this() {
      bodyLen_ = other.bodyLen_;
      module_ = other.module_;
      sub_ = other.sub_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WireMsgHeader Clone() {
      return new WireMsgHeader(this);
    }

    /// <summary>Field number for the "body_len" field.</summary>
    public const int BodyLenFieldNumber = 1;
    private uint bodyLen_;
    /// <summary>
    /// wire: uint16，Protobuf body 字节数（不含头部）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BodyLen {
      get { return bodyLen_; }
      set {
        bodyLen_ = value;
      }
    }

    /// <summary>Field number for the "module" field.</summary>
    public const int ModuleFieldNumber = 2;
    private uint module_;
    /// <summary>
    /// wire: uint8，ClientModule
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Module {
      get { return module_; }
      set {
        module_ = value;
      }
    }

    /// <summary>Field number for the "sub" field.</summary>
    public const int SubFieldNumber = 3;
    private uint sub_;
    /// <summary>
    /// wire: uint8，域内 *MsgSub enum
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Sub {
      get { return sub_; }
      set {
        sub_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WireMsgHeader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WireMsgHeader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BodyLen != other.BodyLen) return false;
      if (Module != other.Module) return false;
      if (Sub != other.Sub) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BodyLen != 0) hash ^= BodyLen.GetHashCode();
      if (Module != 0) hash ^= Module.GetHashCode();
      if (Sub != 0) hash ^= Sub.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BodyLen != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(BodyLen);
      }
      if (Module != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Module);
      }
      if (Sub != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Sub);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BodyLen != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(BodyLen);
      }
      if (Module != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Module);
      }
      if (Sub != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Sub);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BodyLen != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BodyLen);
      }
      if (Module != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Module);
      }
      if (Sub != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Sub);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WireMsgHeader other) {
      if (other == null) {
        return;
      }
      if (other.BodyLen != 0) {
        BodyLen = other.BodyLen;
      }
      if (other.Module != 0) {
        Module = other.Module;
      }
      if (other.Sub != 0) {
        Sub = other.Sub;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BodyLen = input.ReadUInt32();
            break;
          }
          case 16: {
            Module = input.ReadUInt32();
            break;
          }
          case 24: {
            Sub = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BodyLen = input.ReadUInt32();
            break;
          }
          case 16: {
            Module = input.ReadUInt32();
            break;
          }
          case 24: {
            Sub = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
